config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :restrooms, except: [:edit, :destroy]

    namespace :api do
      resources :docs, only: [:index]
    end

    mount API::Base => '/api'

    get '/contact', to: 'contacts#new'
    get "/*id" => 'pages#show', as: :page, format: false
    root 'pages#index'

    resources "contacts", only: [:new, :create]
end

app/models/restroom.rb
# Note:
# In the dataset on which the application is based, UNISEX is coded by 0, ADA
# (accessible) is coded by 1

class Restroom < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search, against: {
    :name => 'A',
    :street => 'B',
    :city => 'C',
    :state => 'D',
    :comment => 'B',
    :directions => 'B',
    :country => 'D',
  },
  using: {tsearch: {dictionary: "english"}},
  ignoring: :accents

  validates :name, :street, :city, :state, presence: true

  geocoded_by :full_address
  after_validation :perform_geocoding

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.name    = geo.address
      obj.street  = geo.address.split(',').first
      obj.city    = geo.city
      obj.state   = geo.state
      obj.country = geo.country_code
    end
  end

  include Rakismet::Model
  rakismet_attrs content: proc {
    name + street + city + state + comment + directions + country
  }

  after_find :strip_slashes

  scope :current, -> {
    Restroom.where('id IN (SELECT MAX(id) FROM restrooms WHERE approved = true GROUP BY edit_id)')
  }

  scope :accessible, -> { where(accessible: true) }
  scope :changing_table, -> { where(changing_table: true) }
  scope :unisex, -> { where(unisex: true) }

  scope :created_since, ->(date) { where("created_at >= ?", date) }
  scope :updated_since, ->(date) { where("updated_at >= ?", date) }

  def full_address
    "#{street}, #{city}, #{state}, #{country}"
  end

  def rated?
    upvote > 0 || downvote > 0
  end

  def rating_percentage
    return 0 unless rated?

    upvote.to_f / (upvote + downvote).to_f * 100
  end

  # PostgreSQL Full-Text Search for the API.
  def self.text_search(query)
    if query.present?
      search(query)
    else
      all
    end
  end

  private

    def strip_slashes
      ['name', 'street', 'city', 'state', 'comment', 'directions'].each do |field|
        attributes[field].try(:gsub!, "\\'", "'")
      end
    end

    def perform_geocoding
      return true if Rails.env == "test"
      return true if ENV["SEEDING_DONT_GEOCODE"]
      geocode
    end
end

app/controllers/api/v1/restrooms.rb
module API
  module V1
    class Restrooms < Grape::API
      include Grape::Kaminari
      paginate per_page: 10, max_per_page: 100

      version 'v1'
      format :json

      resource :restrooms do
        desc "Get all restroom records ordered by date descending."
        params do
          optional :ada, type: Boolean, desc: "Only return restrooms that are ADA accessible."
          optional :unisex, type: Boolean, desc: "Only return restrooms that are unisex."
        end
        get do
          r = Restroom
          r = r.current
          r = r.accessible if params[:ada].present?
          r = r.unisex if params[:unisex].present?

          paginate(r.order(created_at: :desc))
        end

        desc "Perform full-text search of restroom records."
        params do
          optional :ada, type: Boolean, desc: "Only return restrooms that are ADA accessible."
          optional :unisex, type: Boolean, desc: "Only return restrooms that are unisex."
          requires :query, type: String, desc: "Your search query."
        end
        get :search do
          r = Restroom
          r = r.current
          r = r.accessible if params[:ada].present?
          r = r.unisex if params[:unisex].present?

          paginate(r.text_search(params[:query]))
        end

        desc "Search by location."
        params do
          optional :ada, type: Boolean, desc: "Only return restrooms that are ADA accessible."
          optional :unisex, type: Boolean, desc: "Only return restrooms that are unisex."
          requires :lat, type: Float, desc: "latitude"
          requires :lng, type: Float, desc: "longitude"
        end
        get :by_location do
          r = Restroom
          r = r.current
          r = r.accessible if params[:ada].present?
          r = r.unisex if params[:unisex]
          paginate(r.near([params[:lat], params[:lng]], 20, :order => 'distance'))
        end

        desc "Search for restroom records updated or created on or after a given date"
        params do
          optional :ada, type: Boolean, desc: "Only return restrooms that are ADA accessible."
          optional :unisex, type: Boolean, desc: "Only return restrooms that are unisex."
          optional :updated, type: Boolean, desc: "Return restroom records updated (rather than created) since given date"
          requires :day, type: Integer, desc: "Day"
          requires :month, type: Integer, desc: "Month"
          requires :year, type: Integer, desc: "Year"
        end
        get :by_date do
          r = Restroom
          r = r.current
          date = Date.new(params[:year], params[:month], params[:day])
          if params[:updated]
            r = r.updated_since(date)
          else
            r = r.created_since(date)
          end
          r = r.accessible if params[:ada].present?
          r = r.unisex if params[:unisex].present?
          paginate(r.order(created_at: :desc))
        end
      end
    end
  end
end

app/controllers/restrooms_controller.rb
require_relative '../helpers/recaptcha_helper'

class RestroomsController < ApplicationController
  respond_to :html, :json

  before_action :list_restrooms, only: [:index]
  before_action :find_restroom, only: [:show, :update, :edit, :destroy]

  def index
    if params[:nearby]
      render :nearby, layout: false
    else
      respond_with @restrooms
    end
  end

  def new
    if params[:edit_id]
      @restroom = find_restroom
      @restroom.edit_id = params[:edit_id]
      @restroom.approved = false
    elsif params[:guess]
      @restroom = Restroom.new(permitted_params)
      @restroom.reverse_geocode
      render 'new', layout: false
    else
      @restroom = Restroom.new
    end
  end

  def create
    @restroom = Restroom.new(permitted_params)

    # Verify recaptcha code
    recaptcha_response = params['g-recaptcha-response']
    unless RecaptchaHelper.valid_token? recaptcha_response
      flash.now[:error] = I18n.t('helpers.reCAPTCHA.failed')
      render 'new'
      return
    end

    @restroom = SaveRestroom.new(@restroom).call

    if @restroom.errors.empty?
      if @restroom.approved?
        flash[:notice] = I18n.t('restroom.flash.new', name: @restroom.name)
        redirect_to @restroom
      else
        flash[:notice] = I18n.t('restroom.flash.edit', name: @restroom.name)
        redirect_to restroom_path(@restroom.edit_id)
      end
    elsif @restroom.errors.key?(:spam)
      flash[:notice] = I18n.t('restroom.flash.spam')
      render 'new'
    else
      display_errors
      render 'new'
    end
  end

  def update
    if params[:restroom][:downvote]
      Restroom.increment_counter(:downvote, @restroom.id)
    elsif params[:restroom][:upvote]
      Restroom.increment_counter(:upvote, @restroom.id)
    elsif @restroom.update(permitted_params)
      flash[:notice] = I18n.t('restroom.flash.updated')
    else
      display_errors
      render 'edit'
    end

    redirect_to @restroom
  end

private
  def list_restrooms
    @restrooms = Restroom.current.page(params[:page])
    @restrooms = if params[:search].present? || params[:map] == "1"
      @restrooms.near([params[:lat], params[:long]], 20, :order => 'distance')
    else
      @restrooms.reverse_order
    end
  end

  def display_errors
    if @restroom.errors.any?
      errors = @restroom.errors.each do |attribute, message|
        flash[:alert] = I18n.t('restroom.flash.field')
      end
    else
      flash[:alert] = I18n.t('restroom.flash.unexpected')
    end
  end

  def find_restroom
    @restroom = Restroom.find(params[:id])
  end

  def permitted_params
    params.require(:restroom).permit(
      :name,
      :street,
      :city,
      :state,
      :country,
      :accessible,
      :changing_table,
      :unisex,
      :directions,
      :comment,
      :longitude,
      :latitude,
      :edit_id,
      :approved
    )
  end
end

app/helpers/restrooms_helper.rb
module RestroomsHelper
  KILO_DISTANCE_CONVERSION = 1.609344
  def miles_to_kilometers(miles)
    miles * KILO_DISTANCE_CONVERSION
  end
end

app/views/restrooms/_formsubmit.html.haml
%h1= t('restroom.add_new')

= simple_form_for @restroom, :url => restrooms_path, :method => :post, html: {class: 'submit-new-bathroom-form form-vertical'} do |f|
  %h5= t('restroom.required')
  .clearfix
    %button.btn.btn-light-purple.guess-btn{:type => "button", :value => t('restroom.guess_location')}
      = t('restroom.guess_location')
      %i.fa.fa-refresh.fa-spin

  / Add map for preview
  #mapArea.hidden{ data: { latitude: 38.904735, longitude: -77.033812 } }

  .nearby-container.footroom
    // Content of nearby restrooms gets rendered here.

  = f.input :name, :required => true
  = f.input :street, :required => true
  = f.input :city, :required => true
  = f.input :state, :required => true
  = f.input :country, priority: ["United States", "Canada", "United Kingdom"], :required => true, input_html: {class: 'form-control'}
  = f.hidden_field :latitude
  = f.hidden_field :longitude
  = f.hidden_field :edit_id
  = f.hidden_field :approved
  = f.input :accessible, :collection => [[t('restroom.accessible'), true], [t('restroom.not_accessible'), false]], :include_blank => false
  = f.input :unisex, :collection => [[t('restroom.type.unisex'), true], [t('restroom.type.single_stall'), false]], :include_blank => false
  = f.input :changing_table, :collection => [[t('restroom.changing_table'), true], [t('restroom.no_changing_table'), false]], :include_blank => false
  = f.input :directions, :placeholder => t('restroom.directions_hint'), :as => :text, :required => false, :input_html => { :class => "span6" }
  = f.input :comment, :placeholder => t('restroom.comments_hint'), :as => :text, :required => false, :input_html => { :class => "span6" }

  .form-group
    .g-recaptcha{'data-sitekey' => "#{ENV['RECAPTCHA_SITE_KEY']}"}

  / Click to preview location
  %button{type: 'button', class: 'preview-btn linkbutton'}
    = t('restroom.preview')
  = f.button :submit, t('restroom.restsubmit'), :class => "linkbutton"

app/views/restrooms/_restroom.html.haml
- unisex_class = restroom.unisex? ? '' : 'not_unisex'
- accessible_class = restroom.accessible? ? '' : 'not_accessible'
- changing_table_class = restroom.changing_table? ? '' : 'no_changing_table'

%li{ class: "listItem clearfix #{unisex_class} #{accessible_class} #{changing_table_class}",
          data: { id: restroom.id} }
  .listItemImage
    / image tag goes here
  .itemInfo
    .itemName= link_to_unless_current(restroom.name.titleize, restroom)
    .itemStreet="#{restroom.street}, #{restroom.city}, #{restroom.state}"
    - if restroom.rated?
      - rating_class_name = case RatingLevel.for_restroom(restroom)
      - when RatingLevel.green  then 'greenRating'
      - when RatingLevel.yellow then 'yellowRating'
      - when RatingLevel.red    then 'redRating'
      - else ''
      %div{:class => "itemRating #{rating_class_name}"}
        = t('restroom.rating.positive', percentage: restroom.rating_percentage.round)
    - else
      .itemRating= t('restroom.rating.unrated')

  .itemExtraInfo
    .itemDistance
      - if restroom.respond_to?(:distance)
        = restroom.distance.round(2)
        = t("restroom.distance.miles")
        \/
        = miles_to_kilometers(restroom.distance).round(2)
        = t("restroom.distance.kilometers")
    .itemIcons
      - if restroom.unisex?
        .unisexRestroom{:title => t("restroom.type.unisex")}
          %i.fa.fa-transgender-alt.fa-2x
      - if restroom.accessible?
        .ADARestroom{:title => t("restroom.accessible")}
          %i.fa.fa-wheelchair.fa-2x
      - if restroom.changing_table?
        .changingTable{:title => t("restroom.changing_table")}
          %i.fa.fa-child.fa-2x

app/views/restrooms/edit.html.haml
= render "formsubmit"

app/views/restrooms/index.html.haml
.row
  .col-xs-12.headroom
    #filters.clearfix
      .btn-group{:data => {:toggle => "buttons"}}
        %label#ada_filter.filter.btn.btn-light-purple.linkbutton{:title => t("restroom.accessible")}
          %input{:type => "checkbox"}
          %i.fa.fa-wheelchair
        %label#unisex_filter.filter.btn-light-purple.btn.linkbutton{:title => t("restroom.type.unisex")}
          %input{:type => "checkbox"}
          %i.fa.fa-transgender-alt
        %label#changing_table_filter.filter.btn-light-purple.btn.linkbutton{:title => t("restroom.changing_table")}
          %input{:type => "checkbox"}
          %i.fa.fa-child

      .map-toggle-btn.mapToggle.linkbutton.btn-lg.btn-light-purple
        = t('.map-view-button-label')

.restrooms-index-content
  .row
    .col-sm-12.headroom
      #results
        = content_tag 'div', id: 'mapContainer', data: { latitude: params[:lat], longitude: params[:long] } do
          #mapArea
  .row
    .col-sm-12.headroom
      %ul{:class => "restrooms-list", :id => "list"}
        = render @restrooms
        = paginate @restrooms
/ .row
/   .col-xs-12.headroom
/     .restrooms-index-content
/       = content_tag 'div', id: 'map-container', data: { latitude: params[:lat], longitude: params[:long] } do
/         #map-content
/       .restrooms-list
/         = render @restrooms
/         = paginate @restrooms


/ #results.headroom
/   = content_tag 'div', id: 'mapContainer', data: { latitude: params[:lat], longitude: params[:long] } do
/     #mapArea
/   #list.restrooms-list
/     = render @restrooms
/     = paginate @restrooms

app/views/restrooms/nearby.html.haml
- if @restrooms.empty?
  .none
    %p= t('.none')
- else
  %h2= t('.heading')
  %p= t('.body')
  .minimalRestroomList= render @restrooms
  .clearfix

app/views/restrooms/new.html.haml
.row
  .col-sm-12
    .new-restrooms-form-container.form-container
      = render 'formsubmit'

app/views/restrooms/show.html.haml
.row.headroom
  .col-xs-12
    .listItem.showPageItem{"data-id" => @restroom.id}
      = render partial: 'restrooms/restroom', locals: { restroom: @restroom }

.showPageContent
  .row
    .col-xs-12
      .btn-group{role: "group"}
        = link_to restroom_path(restroom: { upvote: true }),
                    method: 'put' do
          %button.btn.btn-lg.btn-success
            %i.fa.fa-thumbs-up
            = t('.thumbs-up-button-label')

        = link_to restroom_path(restroom: { downvote: true }),
                    method: 'put' do
          %button.btn.btn-lg.btn-danger
            %i.fa.fa-thumbs-down
            = t('.thumbs-down-button-label')
  .row.headroom
    .col-xs-12

      %p
        %strong #{t('restroom.directions')}:
        = @restroom.directions
      %p
        %strong #{t('restroom.comments')}:
        = @restroom.comment
      %p= link_to t('restroom.edit.editlisting'), new_restroom_path(id: @restroom.id, restroom_name: @restroom.name, edit_id: @restroom.edit_id)
  .row
    .col-xs-12
      #map
        %div#mapArea{ data: { latitude: @restroom.latitude, longitude: @restroom.longitude } }
      %hr
  .row
    .col-xs-12
      = render partial: 'layouts/disqus_tag', locals: { identifier: "restroom-#{@restroom.id}", title: @restroom.name, url: request.original_url }